### PR TITLE
KMeans clustering features choosing

### PR DESCRIPTION
**Pull request by archv**
The ability to choose what features to cluster is ready for KMeans clustering algorithm.
Used the latest version of dataset-handling-refactoring branch.
Also added plenty of comments to createClusterElements(...)@sup_func.js (line 72 and so on). Please tell what do you think about this commenting style.

While testing I have discovered 2 problems I need help with:
1. Any clustering algorithm uses normalized sets of data. With the new form_reactions I am not sure what do I change. To verify the problem, please add 'print(dataset)' to predict(...)@KMeansClustering.py and clusterize the data. @mtitov , please help.
2. DBScan algorithm makes only one cluster called '-1'. Is that a known problem?

Please review anyways.

### CODE REVIEW

**Comment by archv** [comment]
@maria-grigorieva @mtitov The changes are made.

**Comment by maria-grigorieva** [comment]
I've just tested it on Safari and Chrome, and the number of clusters is still only 5, however I tried to specify 10, 12... @mtitov, could you please check it on your environment? Maybe I just have cached... although I tested it even in incognito mode in Chrome.
And one more issue... I can't understand why, but when the small data sample is chosen from the server (those, with 4 parameters) - JS error appears connected with matrix. @mtitov, could you please check this also?

**Comment by maria-grigorieva** [comment]
@archv, I think there is no need to merge development in your branch, as the next step is to merge it with development. It makes sense only if you are going to work with this branch further. But I suppose no. So, it's better to remove your last merge commit.

**Comment by mtitov** [comment]
@maria-grigorieva I can confirm that server receives the correct value of the requested number of clusters, BUT the correct number is just not represented at UI, also dataset sample with small number of parameters (e.g., 4) is treated correctly (corresponding update of JS file was taken from development branch).

@maria-grigorieva @archv I would suggest to apply the same pre-latest changes (as commit a1c4250, and not 1f41565) to the branch "viewdata-handling" and consider it as a candidate to merge with development instead of clustering-dimensions branch (since viewdata-handling was created based on clustering-dimensions branch, but without 2 latest commits). And before merging with development fix errors mentioned in my previous paragraph (i.e., represent the correct number of clusters at UI)

**Comment by maria-grigorieva** [comment]
This branch was merged into viewdata-handling.

**Pull request closed without merging**
